name: GUITAR BASS PLAYER
favicon: null
layout_spectrum: 0.7678
typography_spectrum: 0.25561
title: FRIENDLYMUSICIAN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a9311'
    - '#0e0307'
    - '#5edceb'
    - '#d0cd0e'
    - '#e26334'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
